
RegisterCommand('newlife', function()
exports['esx_rpchat']:printToChat('Newlife', 'Je hebt je newlife uitgevoerd! je zal over 60 seconden worden gerevived')
Citizen.Wait(10000)
exports['esx_rpchat']:printToChat('Newlife', 'Nog 50 seconden!')
Citizen.Wait(20000) 
exports['esx_rpchat']:printToChat('Newlife', 'Nog 40 seconden!')
Citizen.Wait(30000)
exports['esx_rpchat']:printToChat('Newlife', 'Nog 30 seconden!')
Citizen.Wait(40000)
exports['esx_rpchat']:printToChat('Newlife', 'Nog 10 seconden!')
Citizen.Wait(55000)
exports['esx_rpchat']:printToChat('Newlife', 'Nog 5 seconden!')
Citizen.Wait(60000)
TriggerEvent('esx_ambulancejob:revive')
exports['esx_rpchat']:printToChat('Newlife', 'Je hebt een revive ontvangen!')
end)